### ISSUE TITLE
No issue, just a question

### ISSUE THREAD

**Issue by Enryuu2** [phax/as2-peppol-servlet#1]
Hey Philip,

I created my own keystore as the documentation said i should in servlet project and added a certificate with the domain name. but when i try to sent a message to the server from a as2 client (not yours) i get  an handshake exception PKIX path building failed, unable to find valid certification path to
requested target. After some searching it told me because it was not trustworthy or something. i am totally new to certificates and to be honest i have no clue what i am doing, i have trying to figure this out for a couple of days now but with no luck. message does not even reach doPost() section of servlet. 

Do you have any documentation about certificates? i could not find how certificates with created  for new partners in the framework.

sorry if it is unclear. but just started with java programming and SSL/certificate management  is hard to get my head around.

1. do i need to create truststore as well in code?
2. can AS2open create certificate authority?
3. can AS2open create partner certificates and send them?

kind regards

**Comment by phax** [comment]
Hi!
I need a few background information:
* Are you using http or https connection?
* Do you sign and/or encrypt the messages?
* Do you use synchronous or asynchronous MDN?
* Is the MDN signed and/or encrypted?
Thanks

**Comment by Enryuu2** [comment]
Hello, 

server is on https, 
syncronus mdn and checked with signed mdn (not that i know what it means)
digital signature algorithm = sha-256
message encryption algorytim = 3des
uploading picture of key/store: its development anyway so it can be public

[key used](https://contaxinc-my.sharepoint.com/personal/boschs_contax_com/_layouts/15/guestaccess.aspx?guestaccesstoken=jQg2TU9dnvETZjUCBS%2bLExsUVT6egJpHOaPD%2bfMPlEM%3d&docid=0f5386e8da767473892ae4447d1209f04)

**Comment by phax** [comment]
Okay, so you are trying to send from Mendelson to as2-server.
MDN = Message Disposition Notification = "response message". Synchronous means "as answer via http". Asynchronous would mean "initiate a new http message when response is available".
Signature and Encryption algorithms are okay.

The key alias in the as2-servlet keystore must match the as2-id of sender/receiver in the keystore/truststore.
Keystore: list of private keys for encrypting messages/MDNs (what are my secerts)
Truststore: list of public certificates for verifying signatures etc. (whom do I trust)

hth

**Comment by phax** [comment]
Okay, so you are trying to send from Mendelson to as2-server.
MDN = Message Disposition Notification = "response message". Synchronous means "as answer via http". Asynchronous would mean "initiate a new http message when response is available".
Signature and Encryption algorithms are okay.

The key alias in the as2-servlet keystore must match the as2-id of sender/receiver in the keystore/truststore.
Keystore: list of private keys for encrypting messages/MDNs (what are my secerts)
Truststore: list of public certificates for verifying signatures etc. (whom do I trust)

hth

**Comment by phax** [comment]
Okay, so you are trying to send from Mendelson to as2-server.
MDN = Message Disposition Notification = "response message". Synchronous means "as answer via http". Asynchronous would mean "initiate a new http message when response is available".
Signature and Encryption algorithms are okay.

The key alias in the as2-servlet keystore must match the as2-id of sender/receiver in the keystore/truststore.
Keystore: list of private keys for encrypting messages/MDNs (what are my secerts)
Truststore: list of public certificates for verifying signatures etc. (whom do I trust)

hth

**Comment by phax** [comment]
Okay, so you are trying to send from Mendelson to as2-server.
MDN = Message Disposition Notification = "response message". Synchronous means "as answer via http". Asynchronous would mean "initiate a new http message when response is available".
Signature and Encryption algorithms are okay.

The key alias in the as2-servlet keystore must match the as2-id of sender/receiver in the keystore/truststore.
Keystore: list of private keys for encrypting messages/MDNs (what are my secerts)
Truststore: list of public certificates for verifying signatures etc. (whom do I trust)

hth

**Comment by Enryuu2** [comment]
here is what i am stuck on. the keystore holds certificates but i dont see a truststore in application. does the keystore hold both? 

so lets say key alias is created with "test' how do i assign it as2-id to appication 

This is my expectation of what i thought would happen:

application creates a partner and with a partner comes new certificate assignment that would be sent to them so they can import it to use in the as2 verfication. 

from what i read:
 
the keystore holds one certificate that has prvate key, from what i read i need to create a Server's certifying authority's initial certificate. then i need to sign it somehow and store it back to keystore?   

sorry to be a newby to the field.

**Comment by phax** [comment]
Short question (again): you filed this in the "as2-peppol-servlet" project. Do you want to have a solution for PEPPOL or for something else?
Because in PEPPOL we're using a dynamic partnership factory that is filled dynamically whereas in most other AS2 projects you have fixed (pre-configured or manually configured partners).
In the non-PEPPOL case your central keystore holds your private key plus the public keys of all partners from which you retrieve messages (or MDNs).

The sender signs with his private key and the receiver validates with the public key of the sender.
The sender encrypts with the public key of the receiver and the receiver decrypts with his private key.
hth

**Comment by Enryuu2** [comment]
I had no place to ask you directly so I placed it in a issue. right now it is not PEPPOL specific. just want to be able to connect to server receive message, intercept it do something with it and resend it to receiver. 

For now I would like to learn / implement the non dynamic way. To do that I have done so far: create a keystore using the following command:

keytool -genkeypair -keyalg RSA -alias server_ca -keystore server-certs.p12 -storetype pkcs12 -storepass IqU7FmqE_1vEloz -validity 9999 -keysize 2048 -sigalg SHA256withRSA  

Then I exported the self signed certificate by using the following command:

keytool -exportcert -alias server_ca -file server_ca.cer -keystore server-certs.p12

Note that the alias is the same as it was not before.
I then used the exported cert and imported it Mandelson client.

Then I placed keystore under the AS2Config file and see link for my current project structure:

https://onedrive.live.com/redir?resid=F66C6D84A955D605!33686&authkey=!ABhHEudng0xpHGA&v=3&ithint=photo%2cpng

Development server it is running on is under:

https://gateways0016082696trial.hanatrial.ondemand.com/gateway/as2

**Comment by phax** [comment]
Okay, so the alias is "server_ca". In this case you need a keypair called "server_ca" in your keystore.
I think that the example configuration from https://github.com/phax/as2-server/tree/master/src/main/resources/config might help you. The keystore PW is "test". Relevant files are certs.p12 (keystore), config.xml (configure keystore etc.) and partnerships.xml (definining the connection with keystore aliases).
hth

**Comment by phax** [comment]
So I assume you managed to exchange messages :)
