### ISSUE TITLE
Question: Sending AS2 msg

### ISSUE THREAD

**Issue by Enryuu2** [phax/as2-peppol-servlet#2]
Good day Philip,

i am finally starting to understand your code and how the classes are linked together and added a send module based of Receive module.

Now i need to construct message but i do not understand the parameters that the send module expects.

``` java
getSenderModule().handle(sAction, aBaseMsg, aOptions);
```

Action: a normal string of what?
aBaseMsg: does this accept AS2Message msg = new AS2Message
aOption: why is this different from message and not together i asume these are the message options.

Also the message requires Partnership class but i cant find a method that retrieves a partner based on alias like getPartner(String partnerAlias).

i am sorry to be a pain. but when i got stable implementation i can share it back with you at the very least i can write some implementation documentation in more detail.

i hope you can help me again. i would appreciate it. 

kind regards,

stephan

**Comment by phax** [comment]
Hi!
First of all, why do you add your own sending module - there is one contained in `AS2SenderModule`. And I did not invent this my own - this is a fork from OpenAS2, as it was discontinued for a long time.

The first parameter `sAction` is the internal command key. If a module supports different commands, this is to decide which one to execute. See `canHandle (String, IMessage, Map)` for the most use of action.

The parameter `aBaseMsg` is of type `IMessage` as this is the base class for both `AS2Message`. Before sending you must fill some basic stuff. See `AS2Client.createBasicMessage` for details.

The parameter `aOptions` may contain message specific options that e.g. overwrite settings contained in the partnership factory.

To get a `Partnership` see the interface `IPartnershipFactory` and the derived classes (like `SelfFillingPartnershipFactory`). It also has a `getPartnershipByName` method but usually you need to create a new `Partnership` with one sender and one receiver ID.

hth, Philip

**Comment by Enryuu2** [comment]
Good day Philip,

Thank you for your help.

I am able to send a message now thanks to a good look at AS2ClientBuilder and the steps involved. unfortunate i get a timeout error. what i find weird about this error is that the port does not seem to match the AS2-URL. 

Error by AS2Client: 
 java.net.SocketTimeoutException: Read timed out (local port 53007 to address 10.117.37.62 (vsa1081569.nwtrial.od.sap.biz), remote port 8080 to address 10.117.18.16 (sgw-a1s-03-int.od.sap.biz)) 

While AS2-URL: 

http://as2gateway.org:8280/service/as2-receiver
When you ping host i get different IP.

I am so close to a form based AS2 interface for this project just the final push.

kind regards,

Stephan bosch

**Comment by phax** [comment]
Hi Stephan!
This can have multiple reasons:
1. You may have some special routing in your `etc/hosts` file
2. You have a proxy that is setup/not setup correctly
3. The attribute `CPartnershipIDs.PA_AS2_URL` (`as2_url` - underscore) is the relevant one - please debug and check if it contains the correct URL

Good luck
  Philip

**Comment by phax** [comment]
Btw. short question: are you ready if as2-lib is moved to JDK8 soon?

**Comment by Enryuu2** [comment]
hey,

I have been running project on sdk8 so no problems here.

kind regards,

**Comment by phax** [comment]
Sorry, I didn't notice you edited your comment :(
To turn on debug logging you need to modify the `log4j2.xml` file and set the debug logging from `"info"` to `"debug"` - if you are using Log4J2 ;-)

**Comment by Enryuu2** [comment]
Hello, sorry for late reply. weekend and all. could you send me the log42j configuration file. or is it located somewhere in the projects?

**Comment by phax** [comment]
This heavily depends on your setup...
Please check your dependencies if you have some "log4j" or "slf4j-simple.jar" in your dependencies and let me know

**Comment by Enryuu2** [comment]
Philip it is like your psychic ☺

<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-api</artifactId>
<version>1.7.21</version>
<scope>provided</scope>
</dependency>

<dependency>
<groupId>org.slf4j</groupId>
<artifactId>slf4j-simple</artifactId>
<version>1.7.21</version>
<scope>provided</scope>
</dependency>

Kind regards,

Stephan Bosch
Technical Consultant – CONTAX Nederland B.V.
+31.6.2870.1444 (m)  |  +1.312.475.9706 x1212 (o)
boschs@contax.com<mailto:boschs@contax.com> | http://www.contax.com<http://www.contax.com/> | LinkedIn<https://nl.linkedin.com/in/stephanbosch1>

**Comment by phax** [comment]
Well, I know my code (partially) ;-)

Create a file called `simplelogger.properties` (name is fixed) in folder `src/main/resources/` and content:
```
# SLF4J's SimpleLogger configuration file
# Simple implementation of Logger that sends all enabled log messages, for all defined loggers, to System.err.

# Default logging detail level for all instances of SimpleLogger.
# Must be one of ("trace", "debug", "info", "warn", or "error").
# If not specified, defaults to "info".
org.slf4j.simpleLogger.defaultLogLevel=info

# Logging detail level for a SimpleLogger instance named "xxxxx".
# Must be one of ("trace", "debug", "info", "warn", or "error").
# If not specified, the default logging detail level is used.
#org.slf4j.simpleLogger.log.xxxxx=

# Set to true if you want the current date and time to be included in output messages.
# Default is false, and will output the number of milliseconds elapsed since startup.
org.slf4j.simpleLogger.showDateTime=false

# The date and time format to be used in the output messages.
# The pattern describing the date and time format is the same that is used in java.text.SimpleDateFormat.
# If the format is not specified or is invalid, the default format is used.
# The default format is yyyy-MM-dd HH:mm:ss:SSS Z.
#org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS Z

# Set to true if you want to output the current thread name.
# Defaults to true.
#org.slf4j.simpleLogger.showThreadName=true

# Set to true if you want the Logger instance name to be included in output messages.
# Defaults to true.
#org.slf4j.simpleLogger.showLogName=true

# Set to true if you want the last component of the name to be included in output messages.
# Defaults to false.
#org.slf4j.simpleLogger.showShortLogName=false
```

The `org.slf4j.simpleLogger.defaultLogLevel` property is what you are looking for

**Comment by Enryuu2** [comment]
Hello Philip. 

It seems the timeout i got is because of the receiving end not responding. tested it with 2 applications of as2open. 1 as receiver other as sender and that worked fine. I can see debug messages that have logger.debug. but not where method isdebugenabled() is implemented. but upon reading i found out this method still belongs to the old logger 1.x and can be removed and just use logger.debug instead. maby you could run a find all remove command in eclipse and update project to reflect this?  

Also i tried to use latest helger.common but it is missing classes this project is using so i had to revert back.

**Comment by phax** [comment]
Hi Stephan!
I'm currently transitioning all my projects to Java 8. Therefore I'm running against the SNAPSHOT versions of all libraries - sometimes they are updated multiple times a day and you need to run the "Maven | Update Projects" in Eclipse with "Force Update SNAPSHOTS".

Concerning the logger issue, I will look into it.

Concernng the timeout - maybe you can add a proxy in between (e.g. Fiddler when using Windows) to see the details of the message flow.
hth

**Comment by phax** [comment]
Please re-open if necessary. But 1 year is enough :)
