### ISSUE TITLE
Add support for java 8 annotation targets TYPE_USE and TYPE_PARAMETER

### ISSUE THREAD

**Issue by tsachev** [phax/as2-peppol-servlet#3]
Java 8 adds two new targets for annotations.
- TYPE_USE - here are some examples

```
class MyData implements MyTypedInterface<@Limit(2) MyType> {}

new @Immutable Rock()

(@NonNull String) calculateValue()

void doSomething() throws @Critical IOException();
```

For all possible 16 type uses refer to https://docs.oracle.com/javase/specs/jls/se8/html/jls-4.html#jls-4.11
- TYPE_PARAMETER - is for declaring type parameters like

```
class MyClass<@NonNull T> {}

<@Immutable T> void process(T message);
```

**Comment by tsachev** [comment]
sorry wrong project :(

**Comment by phax** [comment]
Thanks - wanted to just point it out :)

**Comment by phax** [comment]
And I assume you also starred the wrong project ;-)
